EDICION="libro-201112"

ENTRADA="\
	r:extras/cjsjb-partituras-separador-entrada.pdf \
	alabanzas/alabanzas.ly \
	losninnoshebreos/losninnoshebreos.ly \
	resucitoresucito/resucitoresucito.ly \
	venganysubamos/venganysubamos.ly
	"

KIRIE="\
	r:extras/cjsjb-partituras-separador-kirie.pdf \
	sennortenpiedad64/sennortenpiedad64.ly \
	sennortenpiedadlamenor/sennortenpiedadlamenor.ly \
	sennortenpiedadgem/sennortenpiedadgem.ly \
	"

GLORIA="\
	r:extras/cjsjb-partituras-separador-gloria.pdf \
	gloriacombo/gloriacombo.ly \
	"

ALELUYA="\
	r:extras/cjsjb-partituras-separador-aleluya.pdf \
	aleluyaalcreador/aleluyaalcreador.ly \
	buscaprimero/buscaprimero3.ly \
	cantaaleluya/cantaaleluya.ly \
	honorygloriaati/honorygloriaati.ly \
	"

OFERTORIO="\
	r:extras/cjsjb-partituras-separador-ofertorio.pdf \
	hemosentregado/hemosentregado.ly \
	"

SANTO="\
	r:extras/cjsjb-partituras-separador-santo.pdf \
	santogenrv/santogenrv.ly \
	santolentoytriste/santolentoytriste.ly \
	santosanto/santosanto.ly \
	"
CORDERO="\
	r:extras/cjsjb-partituras-separador-cordero.pdf \
	corderodedioscococo/cococo.ly \
	corderodediosflechitas/corderoflechitas.ly \
	corderodediosgflores/msjbcordero3.ly \
	corderodediosmejia/corderodedios2.ly \
	corderodediosrvaldes/corderorvaldes.ly \
	"
COMUNION="\
	r:extras/cjsjb-partituras-separador-comunion.pdf \
	confiareenyahve/confiareenyahve.ly \
	jesusamigo/jesusamigo-bm.ly \
	misionerodedios/misionerodedios.ly \
	navidadnavidad/navidadnavidad.ly \
	"
SALIDA="\
	r:extras/cjsjb-partituras-separador-salida.pdf \
	elfarol/elfarol.ly \
	"
